services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    restart: always

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: npm run dev
  
  worker:
    build: .
    command: npm run worker
    depends_on: 
      - redis
      - kafka
    env_file:
      - .env
    volumes:
      - .:/app   
  consumer:
    build: .
    command: npm run consumer
    depends_on:
      - kafka
      - redis
    env_file:
      - .env
    volumes:
      - .:/app